<script>
	import DoneTable from '$lib/components/done/DoneTable.svelte';
	const data = {
		records: [
			{
				id: 2,
				created_time: '2024-07-26 15:10:30+00',
				user_id: 2,
				type: 'task',
				short: 'Follow up on leads',
				long: 'Contact potential customers from the lead list',
				file_url: null,
				archive: true,
				disagreeable_reply: "I don't have the lead list.",
				who: 'Sarah Johnson',
				user_full_name: 'Sarah Johnson',
				done: false,
				tags: ['Tag3']
			},
			{
				id: 4,
				created_time: '2024-07-26 17:20:00+00',
				user_id: 4,
				type: 'email',
				short: 'Urgent: Server issue',
				long: 'Our main server is down. Need to resolve immediately.',
				file_url: null,
				archive: false,
				disagreeable_reply: 'This is a major issue, we need to fix it ASAP.',
				who: 'Jane Smith',
				user_full_name: 'Jane Smith',
				done: false,
				tags: ['Tag4', 'Tag1']
			},
			{
				id: 5,
				created_time: '2024-07-26 18:25:15+00',
				user_id: 5,
				type: 'task',
				short: 'Prepare report',
				long: 'Generate quarterly sales report for Q2 2024',
				file_url: null,
				archive: false,
				disagreeable_reply: "I don't have access to the sales data.",
				who: 'Robert Johnson',
				user_full_name: 'Robert Johnson',
				done: false,
				tags: ['Tag1', 'Tag3']
			},
			{
				id: 8,
				created_time: '2024-07-26 21:40:00+00',
				user_id: 8,
				type: 'task',
				short: 'Research competitors',
				long: 'Gather data on our top 3 competitors',
				file_url: null,
				archive: true,
				disagreeable_reply: "I don't have access to competitor data.",
				who: 'Sophia Wilson',
				user_full_name: 'Sophia Wilson',
				done: false,
				tags: ['Tag6']
			},
			{
				id: 10,
				created_time: '2024-07-26 23:50:30+00',
				user_id: 10,
				type: 'email',
				short: 'Event invitation',
				long: "You're invited to the annual company retreat.",
				file_url: null,
				archive: false,
				disagreeable_reply: "I can't make it to the retreat this year.",
				who: 'Olivia Anderson',
				user_full_name: 'Olivia Anderson',
				done: false,
				tags: ['Tag2']
			},
			{
				id: 11,
				created_time: '2024-07-27 00:55:45+00',
				user_id: 11,
				type: 'task',
				short: 'Update website content',
				long: 'Update the company website with new content and images.',
				file_url: null,
				archive: false,
				disagreeable_reply: "I don't have access to update the website.",
				who: 'Benjamin Taylor',
				user_full_name: 'Benjamin Taylor',
				done: false,
				tags: ['Tag4', 'Tag5']
			},
			{
				id: 14,
				created_time: '2024-07-27 04:10:30+00',
				user_id: 14,
				type: 'task',
				short: 'Organize files',
				long: 'Organize and backup all project files for the last quarter.',
				file_url: null,
				archive: false,
				disagreeable_reply: "I don't have access to the project files.",
				who: 'Isabella Garcia',
				user_full_name: 'Isabella Garcia',
				done: false,
				tags: ['Tag3', 'Tag6']
			},
			{
				id: 1,
				created_time: '2024-07-26 14:42:00+00',
				user_id: 1,
				type: 'email',
				short: 'Important email',
				long: 'This is an important email from John',
				file_url: null,
				archive: false,
				disagreeable_reply: "I don't have time for that right now.",
				who: 'John Doe',
				user_full_name: 'John Doe',
				done: false,
				tags: ['Tag4']
			},
			{
				id: 3,
				created_time: '2024-07-26 16:15:45+00',
				user_id: 3,
				type: 'note',
				short: 'Meeting notes',
				long: 'Notes from the team meeting on 7/26/2024',
				file_url: null,
				archive: false,
				disagreeable_reply: 'I missed some parts of the meeting.',
				who: 'Michael Lee',
				user_full_name: 'Michael Lee',
				done: true,
				tags: ['Tag2', 'Tag3']
			},
			{
				id: 7,
				created_time: '2024-07-26 20:35:45+00',
				user_id: 7,
				type: 'email',
				short: 'Job opening',
				long: "We're hiring for a new software engineer position.",
				file_url: null,
				archive: false,
				disagreeable_reply: "I don't have a large network to share with.",
				who: 'David Lee',
				user_full_name: 'David Lee',
				done: false,
				tags: ['Tag5']
			},
			{
				id: 6,
				created_time: '2024-07-26 19:30:30+00',
				user_id: 6,
				type: 'note',
				short: 'Design ideas',
				long: 'Brainstorming design ideas for the new project.',
				file_url: null,
				archive: false,
				disagreeable_reply: "I don't have any design skills.",
				who: 'Emily Davis',
				user_full_name: 'Emily Davis',
				done: true,
				tags: ['Tag1', 'Tag3']
			},
			{
				id: 12,
				created_time: '2024-07-27 02:00:00+00',
				user_id: 12,
				type: 'note',
				short: 'Meeting agenda',
				long: 'Agenda for the upcoming project meeting.',
				file_url: null,
				archive: false,
				disagreeable_reply: "I won't be able to attend the meeting.",
				who: 'Ava Martinez',
				user_full_name: 'Ava Martinez',
				done: true,
				tags: ['Tag2', 'Tag4']
			},
			{
				id: 13,
				created_time: '2024-07-27 03:05:15+00',
				user_id: 13,
				type: 'email',
				short: 'Project update',
				long: "Here's an update on the current project status.",
				file_url: null,
				archive: false,
				disagreeable_reply: 'I have some concerns about the project timeline.',
				who: 'Joseph Brown',
				user_full_name: 'Joseph Brown',
				done: false,
				tags: ['Tag6', 'Tag4']
			},
			{
				id: 9,
				created_time: '2024-07-26 22:45:15+00',
				user_id: 9,
				type: 'note',
				short: 'Customer feedback',
				long: 'Compiled feedback from customers about our product',
				file_url: null,
				archive: false,
				disagreeable_reply: "I didn't receive any customer feedback.",
				who: 'William Thompson',
				user_full_name: 'William Thompson',
				done: true,
				tags: ['Tag1']
			},
			{
				id: 15,
				created_time: '2024-07-27 05:15:45+00',
				user_id: 15,
				type: 'note',
				short: 'Training materials',
				long: 'New employee training materials for onboarding',
				file_url: null,
				archive: false,
				disagreeable_reply: 'I have some feedback on the training materials.',
				who: 'Mia Hernandez',
				user_full_name: 'Mia Hernandez',
				done: true,
				tags: ['Tag4', 'Tag3', 'Tag5']
			}
		]
	};
</script>

<div class="h-full overflow-y-auto">
	<DoneTable {data} />
</div>
